version : '2'

networks:
  mqtt:
    driver: bridge

services:

  database:
    image: mysql
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql:rw
    networks:
      - mqtt
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "mosquitto"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "123456"
      MYSQL_ROOT_PASSWORD: "123456"

  mosquitto:
    build: .
    ports:
      - "1883:1883"
    links:
      - "database:database"
    networks:
      - mqtt
    restart: always
